[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "fiona>=1.10.1",
    "geoalchemy2>=0.20.0",
    "geopandas>=1.1.4",
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    "joblib>=1.5.3",
    "jupyterlab>=4.6.3",
    "networkx>=3.6.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyproj>=3.7.2",
    "pyrosm>=0.13.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-dotenv>=1.2.3",
    "ruff>=0.16.5",
    "scikit-learn>=1.9.0",
    "shapely>=2.1.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]
